// Views barrel export

export { LandingView } from './LandingView'
export { CoachLandingView } from './CoachLandingView'
export { IntegrationView } from './IntegrationView'
export { InsightsView } from './InsightsView'
export { ProtocolsView } from './ProtocolsView'
export { CoachView } from './CoachView'
export { ApiView } from './ApiView'
export { AdminView } from './AdminView'
export { ClientsView } from './ClientsView'
export { UserDetailView } from './UserDetailView'
export { DataView } from './DataView'
export { StyleDemoView } from './StyleDemoView'
export { default as CurveStyleDemoView } from './CurveStyleDemoView'
